# Generated by Django 5.1.6 on 2025-03-10 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admins',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='Analytics',
            new_name='Analytic',
        ),
        migrations.RenameModel(
            old_name='CarbonFootprints',
            new_name='CarbonFootprint',
        ),
        migrations.RenameModel(
            old_name='Carts',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Recommendations',
            new_name='Recommendation',
        ),
        migrations.RenameModel(
            old_name='Refunds',
            new_name='Refund',
        ),
        migrations.RenameModel(
            old_name='Shippings',
            new_name='Shipping',
        ),
        migrations.RenameModel(
            old_name='Supports',
            new_name='Support',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('eco_score', models.FloatField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.seller')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
