# Generated by Django 5.1.6 on 2025-05-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
