# Generated by Django 5.1.6 on 2025-05-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_cart_product_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
