# Generated by Django 5.2.1 on 2025-05-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'ยังไม่จัดส่ง'), ('shipped', 'ส่งพัสดุแล้ว'), ('in_transit', 'กำลังขนส่ง'), ('delivered', 'จัดส่งสำเร็จ'), ('failed', 'จัดส่งล้มเหลว')], default='pending', max_length=20),
        ),
    ]
