# Generated by Django 5.2.1 on 2025-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_shipping_last_updated_shipping_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการตรวจสอบ'), ('confirmed', 'ชำระเงินสำเร็จ'), ('failed', 'ชำระเงินล้มเหลว')], default='pending', max_length=20),
        ),
    ]
